-- 코드를 작성해주세요

SELECT CASE 
when DATE_FORMAT(DIFFERENTIATION_DATE,"%m") <4 then '1Q'
when DATE_FORMAT(DIFFERENTIATION_DATE,"%m") <7 then '2Q'
when DATE_FORMAT(DIFFERENTIATION_DATE,"%m") <10 then '3Q'
when DATE_FORMAT(DIFFERENTIATION_DATE,"%m") <13 then '4Q'
END AS QUARTER, COUNT(*) as ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER