-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(price * sales) as TOTAL_SALES
FROM BOOK natural join AUTHOR natural join BOOK_SALES as BS
WHERE year(BS.SALES_DATE) =2022 and month(BS.SALES_DATE) = 1
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY desc;