-- 코드를 작성해주세요

SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO as A
WHERE A.ITEM_ID in (Select B.ITEM_ID
                 FROM ITEM_TREE as B JOIN ITEM_INFO as C on B.PARENT_ITEM_ID=C.ITEM_ID
                 WHERE C.RARITY = 'RARE')
ORDER BY A.ITEM_ID DESC;